# Generated by Django 5.0.7 on 2024-11-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_croprecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropRecommendation',
        ),
    ]
